# Generated by Django 2.2 on 2020-03-13 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cami',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_no', models.CharField(blank=True, max_length=255, null='', verbose_name='卡号')),
                ('card_pwd', models.CharField(blank=True, max_length=255, null='', verbose_name='卡密')),
                ('status', models.BooleanField(default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '卡密列表',
                'verbose_name_plural': '卡密列表',
                'db_table': 'cami',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='分类名称')),
                ('desc', models.CharField(blank=True, max_length=100, null='', verbose_name='分类描述')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='PayRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_no', models.CharField(max_length=100, unique=True, verbose_name='支付单号')),
                ('pay_money', models.FloatField(verbose_name='支付金额')),
                ('pay_time', models.DateTimeField(verbose_name='支付时间')),
                ('status', models.BooleanField(default=False, verbose_name='支付状态')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'db_table': 'pay_record',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='产品名称')),
                ('price', models.FloatField(default=1.0, verbose_name='销售价格(元)')),
                ('cami_type', models.PositiveSmallIntegerField(default=1, verbose_name='卡密类型')),
                ('desc', models.CharField(blank=True, max_length=100, null='', verbose_name='商品描述')),
                ('status', models.BooleanField(default=True, verbose_name='上架状态')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairpin.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '产品列表',
                'verbose_name_plural': '产品列表',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_no', models.CharField(max_length=100, verbose_name='订单号')),
                ('status', models.PositiveSmallIntegerField(default=0, verbose_name='订单状态')),
                ('cami', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairpin.Cami', verbose_name='卡密')),
                ('pay_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairpin.PayRecord', verbose_name='支付记录')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairpin.Product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单记录',
                'verbose_name_plural': '订单记录',
                'db_table': 'order',
            },
        ),
        migrations.AddField(
            model_name='cami',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairpin.Product', verbose_name='产品'),
        ),
    ]
